### ISSUE TITLE
Database design and implementation

### ISSUE THREAD

**Issue by florentianayuwono** [florentianayuwono/DigitalIT#8]
As far as I understand, we will need some kind of nested databases for the users. This is what the structure I have in my mind right now:

- Main database `user_account` that stores all users with its basic information that is required upon registration (full name, email, password, phone number)
- Each user, will have its own databases: 1) `BusinessData` that stores all information about its business and 2) `FinancialData` that stores all information about its financial condition
- `BusinessData`, in turn, could also have multiple databases. For example, `ProductData` that stores information about the products (type, price, cost, etc.)
- and so on and so forth

I have been searching for how to implement this database inside database kind of thing in psql, but so far there is kind of limitation around this (?) I might be wrong. Here are the results so far:

- Some suggest using array, but I do not think hard coding the array is neat (?)
- Some suggest using [hstore](https://www.postgresql.org/docs/current/hstore.html), while I do not really understand fully the documentation, but I don't think hstore can accommodate for our needs (?)
- Some suggest modifying the [data type](https://www.quora.com/How-can-I-create-a-nested-table-in-PostgreSQL). So far this is kind of the best solution I can get, but I am not sure and need opinions

Do you know other, better, solutions for this? Is it possible if we can create multiple databases, but somehow connect them using the same `user_id`? So we can have `user_account`, `business_data`, `financial_data`, `product_data`, but all of them somehow has the same `user_id`, so we can easily update and modify. But I am not sure about this because of the possibility of these problems:

- Let's say we delete one user in `user_account`. Then the `user_id` will also disappear right? But then how to also make other data with the same `user_id` automatically disappear?
- Can we truly have the automated generated `user_id` that automatically linking all the databases? Since the order of filling the databases might not be the same for all users. For example: Let's say we have `firstUser` with `user_id 1` and `secondUser` with `user_id 2`. But `secondUser` insert the `business_data` faster than `firstUser`, so if we only rely on psql generating key, obviously `secondUser` will have `business_id 1` in `business_data`.

**Comment by KamiliArsyad** [comment]
Don't worry we can totally do that and it's actually quite simple to do :) 
So what we need to do for our schema is in our digitalIT database, we create multiple tables.
I have already created an example in our current application in which our database has two tables: `user_account` and `projects`. Although the `projects` table is currently there only as an example, you can see how each project have a `manager_id` and that `manager_id` is something that we call a _**foreign key**_ that refers/links to `user_id` of the `user_account`.

You can also refer to the rough diagram of our project that we have in which I model each object (user and product) as separate entities that each have their own data models (which will be implemented as tables in our case) that might link with other objects' data models.

As for automatically generated user_id and how to handle that, worry not because there are common procedures to handle our database as long as the design is clearly drawn. We can discuss the technicalities later in a zoom discussion or something soon but as far as we're concerned, we won't need to create this _nested databases_ thing 👍
