### ISSUE TITLE
Quick Note About Files

### ISSUE THREAD

**Issue by KamiliArsyad** [florentianayuwono/DigitalIT#9]
In the nice new `react-dev` branch it appears that some stuff were being cleaned. Just a quick note, though, the `package.json` and `package-lock.json` in the root folder is different than the ones in the `frontend` folder. The one in the root folder is used for the stack as a whole including the API and the front end, and the one in the `frontend` folder is only for the react part (which usually contains quite a handful of dependencies). So I think you gotta add them back.

_ps I'm not really used to these issues stuff so I don't know if this has the right label or not._

**Comment by florentianayuwono** [comment]
Yes, the `package.json` and `package-lock.json` on the `react-dev` branch are originally from the root folder. I delete the files from the frontend folder instead. But I have not tested them yet, since it is likely that I will try building the react and integrate it with the html for the pages we have right now.

**Comment by florentianayuwono** [comment]
@KamiliArsyad I am currently having an issue inside `react-dev` branch. I am trying to develop the frontend, but cannot run it. So I decide to solve issue inside backend, but I got confused with the error message. Can you please help with the dependencies on backend? I have written the work for `businessData` etc., but cannot test it since cannot run huhu :"))) sorry for messing up

**Comment by KamiliArsyad** [comment]
Alright let me try solving it

**Comment by KamiliArsyad** [comment]
@florentianayuwono 
It appears that there were a lot of changes and I can't really keep track of everything inside my head. I can't also find the frontend folder in the branch (?)

I think it's better if we discuss about the changes first before doing further fix/development. I'll just contact you and see if we can arrange a meet :) but don't worry there shouldn't be a lot of fix.

For now, I'll try deploying our main branch to Heroku ASAP
